[tool.poetry]
name = "course-work-1"
version = "0.1.0"
description = "Курсовая работа №1"
authors = ["Ivan Sokolskiy <Gladtycoon@gmail.com>"]
license = "SkyPro"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
requests = "^2.32.5"
pandas = "^2.3.3"
openpyxl = "^3.1.5"
python-dotenv = "^1.2.1"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"
pytest-html = "^4.1.1"
black = "^26.1.0"
flake8 = "^7.3.0"
isort = "^7.0.0"
mypy = "^1.19.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"